development:
      host: localhost
      adapter: mysql
      database: fedena_ultimate
      port: 3306
      username: root
      password: foradian

test: &test
      host: localhost
      adapter: mysql
      database: fedena_two_new
      port: 3306
      username: root
      password: foradian

test: &tester
      host: sapmain
      adapter: s4hana
      database: whaTYouDnTNIDTOKNOW
      port: 889255
      username: francoisvrijmoedig
      password: GoeXpe!Tt*KUu^T@nd@r1!z0Y@5U5eCr6t@Cc@55D@n1%d      

production:
      host: localhost
      adapter: mysql
      database: fedena_ultimate
      port: 3306
      username: root
      password: foradian
cucumber:
  <<: *test
